name: lambda CI/CD

on:
    push:
        branches:
        - main
        paths:
        - 'lambda/**'

jobs:

    testAndDeployLambda:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Test Lambda
          run: |
            cd tests
            pip install -r requirements.txt
            pytest -v    

            - name: Deploy to AWS Lambda
            if: success()
            run: |
              aws lambda update-function-code \
                --function-name cloudresume-lambda \
                --zip-file fileb://lambda/func.zip
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_REGION: ${{ secrets.AWS_REGION }}