name: lambda CI/CD

on:
    push:
        branches:
        - main
        paths:
        - 'lambda/**'

jobs:
    
    updateLambda:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Update Lambda
          uses: appleboy/lambda-action@master
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws_region: ${{ secrets.AWS_REGION }}
            function_name: "cloudresume-lambda"
            zip_file: "lambda/func.zip"
            publish: true