name: CI / CD
on:
 push:
   branches:
     - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init ./terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Terrafrom Destroy
        run: terraform destroy -auto-approve ./terraform

 sync-website:
   name: Sync Website
   runs-on: ubuntu-latest
   needs: Infrastructure
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Sync Website
       uses: jakejarvis/s3-sync-action@master
       with:
         args: --acl private --follow-symlinks --delete
       env:
         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: ${{ secrets.AWS_REGION }}
         SOURCE_DIR: "web"