name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Check for Terraform changes
        id: terraform-changes
        run: |
          terraform init -backend=false
          terraform fmt -check -recursive
          terraform validate
          echo "::set-output name=changes::$(git diff --exit-code || echo 'true')"

      - name: Terraform Apply
        if: steps.terraform-changes.outputs.changes == 'true'
        run: |
          cd terraform
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          aws s3 cp tfplan s3://my-tfstate-bucket-resume/tfplan
          aws s3 cp terraform.tfstate s3://my-tfstate-bucket-resume/terraform.tfstate

  sync-website:
    name: Sync Website
    runs-on: ubuntu-latest
    needs: terraform-apply
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync Website
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "web"
