name: Deploy Infrastructure, Test the Lambda-Function
on:
    push:
        branches:
        - master
jobs:

    testLambda:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Test Lambda
          run: |
            cd tests
            pip install -r requirements.txt
            pytest -v

    deployInfrastructure:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: 'web'